modLoader="javafml"
loaderVersion="[35,)"
license="MIT"
issueTrackerURL="https://github.com/juan-db/noteblock-plus/issues"
displayURL="https://github.com/juan-db/noteblock-plus"
[[mods]]
modId="noteblock"
version="1.0"
displayName="Noteblock+"
authors="Juan de Bruin"
description="Decrease the pitch of noteblocks with shift + right click."
